--------------------------------------------------------------------------------
-- $Beschreibung:
-- Indizes und Constraints auf der Temp-Tabelle erzeugen  
--------------------------------------------------------------------------------

CREATE INDEX HDAK_OK_I_TMP ON TMP_KRDB_DA_TABLE_KTB_HST
(HDAK_KONTO_ID,HDAK_MAND_SL) LOCAL
LOGGING
TABLESPACE ODSKR_INDX
PARALLEL 32 
PCTFREE    0
INITRANS   2
MAXTRANS   255
STORAGE    ( 
INITIAL          64K
    NEXT             1M
    MAXSIZE          UNLIMITED
    MINEXTENTS       1
    MAXEXTENTS       UNLIMITED
    PCTINCREASE      0
    BUFFER_POOL      DEFAULT
   );

ALTER INDEX HDAK_OK_I_TMP NOPARALLEL;

CREATE UNIQUE INDEX HDAK_PK_TMP ON TMP_KRDB_DA_TABLE_KTB_HST
(HDAK_IF)
LOGGING
TABLESPACE ODSKR_INDX
PARALLEL 32 
PCTFREE    0
INITRANS   2
MAXTRANS   255
STORAGE    ( 
INITIAL          64K
    NEXT             1M
    MAXSIZE          UNLIMITED
    MINEXTENTS       1
    MAXEXTENTS       UNLIMITED
    PCTINCREASE      0
    BUFFER_POOL      DEFAULT
   );

ALTER INDEX HDAK_PK_TMP NOPARALLEL;

CREATE UNIQUE INDEX HDAK_ID_FI_TMP ON TMP_KRDB_DA_TABLE_KTB_HST
(DECODE("HDAK_GUELTIG_KZ",'J',"HDAK_MAND_SL"||' '||"HDAK_KONTO_ID",NULL))
LOGGING
TABLESPACE ODSKR_INDX
PARALLEL 32 
PCTFREE    0
INITRANS   2
MAXTRANS   255
STORAGE    ( 
INITIAL          64K
    NEXT             1M
    MAXSIZE          UNLIMITED
    MINEXTENTS       1
    MAXEXTENTS       UNLIMITED
    PCTINCREASE      0
    BUFFER_POOL      DEFAULT
   );

ALTER INDEX HDAK_ID_FI_TMP NOPARALLEL;

ALTER TABLE TMP_KRDB_DA_TABLE_KTB_HST ADD ( 
CONSTRAINT HDAK_PK_TMP 
PRIMARY KEY 
(HDAK_IF)
USING INDEX HDAK_PK_TMP 
ENABLE NOVALIDATE); 

ALTER TABLE TMP_KRDB_DA_TABLE_KTB_HST ADD ( 
CONSTRAINT HDAK_HPAK_FK_TMP 
FOREIGN KEY (HDAK_HPAK_IF) 
REFERENCES PARTNERKONTEN_HST (HPAK_IF) 
ENABLE NOVALIDATE);

ALTER TABLE TMP_KRDB_DA_TABLE_KTB_HST ADD ( 
CONSTRAINT HDAK_KOK5_FK_TMP 
FOREIGN KEY (HDAK_KOK5_IF) 
REFERENCES KRDB_KORDOBA_KONTEN (KOK5_IF) 
ENABLE NOVALIDATE);

