--------------------------------------------------------------------------------
-- $Beschreibung:
-- Grants zuweisen  
--------------------------------------------------------------------------------

GRANT SELECT ON TMP_KRDB_DA_TABLE_KTB_HST TO READ_BAISMART;
GRANT SELECT ON TMP_KRDB_DA_TABLE_KTB_HST TO READ_ODS;
GRANT SELECT ON TMP_KRDB_DA_TABLE_KTB_HST TO WRITE_BAISMART;
GRANT DELETE ON TMP_KRDB_DA_TABLE_KTB_HST TO WRITE_ODS;
GRANT INSERT ON TMP_KRDB_DA_TABLE_KTB_HST TO WRITE_ODS;
GRANT UPDATE ON TMP_KRDB_DA_TABLE_KTB_HST TO WRITE_ODS;
GRANT SELECT ON TMP_KRDB_DA_TABLE_KTB_HST TO RISKMART;
GRANT SELECT ON TMP_KRDB_DA_TABLE_KTB_HST TO KAMART WITH GRANT OPTION;
GRANT SELECT ON TMP_KRDB_DA_TABLE_KTB_HST TO PVMART;
GRANT SELECT ON TMP_KRDB_DA_TABLE_KTB_HST TO BNCWMART;
GRANT SELECT ON TMP_KRDB_DA_TABLE_KTB_HST TO BO_READ;
GRANT SELECT ON TMP_KRDB_DA_TABLE_KTB_HST TO BAISMART;
GRANT SELECT ON TMP_KRDB_DA_TABLE_KTB_HST TO UC4;
GRANT SELECT ON TMP_KRDB_DA_TABLE_KTB_HST TO FUNDMART;
GRANT SELECT ON TMP_KRDB_DA_TABLE_KTB_HST TO SCMART;
GRANT SELECT ON TMP_KRDB_DA_TABLE_KTB_HST TO MART;
GRANT SELECT ON TMP_KRDB_DA_TABLE_KTB_HST TO PV_READ;
GRANT SELECT ON TMP_KRDB_DA_TABLE_KTB_HST TO ZEBMART;
GRANT SELECT ON TMP_KRDB_DA_TABLE_KTB_HST TO GBSMART;
GRANT SELECT ON TMP_KRDB_DA_TABLE_KTB_HST TO SMMART;
GRANT SELECT ON TMP_KRDB_DA_TABLE_KTB_HST TO APP_SAS_RISK;
GRANT SELECT ON TMP_KRDB_DA_TABLE_KTB_HST TO RETAIL_MART;
GRANT SELECT ON TMP_KRDB_DA_TABLE_KTB_HST TO GFRSMART;
GRANT SELECT ON TMP_KRDB_DA_TABLE_KTB_HST TO APP_SAS_PZM;
GRANT SELECT ON TMP_KRDB_DA_TABLE_KTB_HST TO APP_SAS_MLR;
GRANT SELECT ON TMP_KRDB_DA_TABLE_KTB_HST TO APP_SAS_ADA;
GRANT SELECT ON TMP_KRDB_DA_TABLE_KTB_HST TO BDMART;
GRANT SELECT ON TMP_KRDB_DA_TABLE_KTB_HST TO APP_SAS_VCR;
